# ==================
# Environment
# ==================
environment: production

# ==================
# Base
# ==================
url: "https://alexpate.uk"

# ==================
# Assets
# ==================
assets:
    cachebust: hard
    debug: false
    cache: true
    gzip: [text/css, application/javascript]