# ==================
# Environment
# ==================
environment: production

# ==================
# Base
# ==================
url: "https://alexpate.uk"

# ==================
# Assets
# ==================
assets:
  cache: true
  cachebust: hard
  css_compressor: sass
  js_compressor: uglifier
  debug: false
  sources:
    - _assets/css_src
    - _assets/js
    - _assets/img
    - uploads
  features:
    automatic_img_size: false
  gzip: [text/css, application/javascript]