# ==================
# Environment
# ==================
environment: production

# ==================
# Base
# ==================
url: "http://dev.alexpate.uk"

# ==================
# Assets
# ==================
assets:
    baseurl: http://d1712ben527am7.cloudfront.net/
    cachebust: hard
    debug: false
    cache: true
    gzip: [text/css, application/javascript]