version: 2
jobs:
  build:
    node:
      version: 8.2.0
    steps:
      - checkout
      - run: npm run build
  deploy_staging:
    steps:
      - checkout
      - run: aws s3 sync public/ s3://${STAGING_BUCKET} --region us-east-1 --cache-control "max-age=31536000" --delete
      - run: aws cloudfront create-invalidation --distribution-id ${STAGING_CLOUDFRONT_DISTRIBUTION} --paths '/*'
    filters:
      branches:
        only:
          - staging
  deploy_production:
    steps:
      - checkout
      - run: aws s3 sync public/ s3://${PRODUCTION_BUCKET} --region us-east-1 --cache-control "max-age=31536000" --delete
      - run: aws cloudfront create-invalidation --distribution-id ${PRODUCTION_CLOUDFRONT_DISTRIBUTION} --paths '/*'
    filters:
      branches:
        only:
          - master