version: 2.0

jobs:
  build:
    node:
      version: 8.2.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  deploy:
    machine:
        enabled: true
    steps:
      - checkout
      - run: sudo pip install awscli
      - run: aws s3 sync public/ s3://${BUCKET} --region us-east-1 --cache-control "max-age=31536000" --delete
      - run: aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION} --paths '/*'

workflows:
  version: 2
  deploy-production:
    jobs:
      - build
      - deploy:
        requires:
            - build
          filters:
            branches:
              only:
                - master
          context: site-production

  deploy-staging:
    jobs:
      - build
      - deploy:
        requires:
            - build
          filters:
            branches:
              only:
                - feature/circle-2
          context: site-staging