name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to S3
        uses: actions/aws/cli@master
        with:
          args: 's3 sync public s3://${{secrets.BUCKET}} --region us-east-1 --cache-control "max-age=31536000" --delete'
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: Invalidate Cloudfront
        uses: actions/aws/cli@master
        with:
          args: 'cloudfront create-invalidation --distribution-id ${{secrets.CLOUDFRONT_DISTRIBUTION}} --paths "/*"'
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
